apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  labels:
    purpose: deployment-demo
    project: roboshop
    app: nginx
spec:
  type: LoadBalancer
  selector:
    purpose: deployment-demo
    project: roboshop
    app: nginx
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: "{{ .Values.deployment.targetPort }}" # container port